name: Unit, and lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit:
    uses: ./.github/workflows/unit.yml
  lint:
    uses: ./.github/workflows/lint.yml
