name: Checks and tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Run ESLint
        run: node_modules/.bin/next lint --quiet
      - name: Run Prettier
        run: node_modules/.bin/prettier --check "**/*.{js,css,md,json,jsx,ts,tsx}"
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          start: npm run dev
