
name: Tests

on: [push]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3

  e2e:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Cypress run
          env:
            POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          uses: cypress-io/github-action@v2
          with:
            build: npm install
            start: npm run dev
