name: Unit Tests

on:
  workflow_call

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run Tests
      run: npm run test:coverage
    - name: Sync Coverage Badges
      run: npm run test:coverage:badge
        
